name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*.x"
      - "master"
  push:
    branches:
      - "*.x"
      - "master"
      - "develop"
  schedule:
    - cron: "42 3 * * 1"

jobs:
  phpunit:
    name: "Tests"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        name:
          - 'PHP 7.2 tests (Symfony 4.4)'
          - 'PHP 7.3 tests (Symfony 4.4)'
          - 'PHP 7.4 tests (Symfony 4.4)'
          - 'PHP 7.4 tests (Symfony 5.1)'
          - 'PHP 8.0 tests (Symfony 5.4)'
          - 'PHP 8.0 tests (Symfony 6.0)'
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
        symfony-version:
          - "4.4.*"
          - "5.4.*"
          - "6.0.*"
        deps:
          - "lowest"
          - "highest"
        coverage:
          - "false"
        include:
          - php-version: '7.2'
            symfony-version: 4.4.*
            deps: "highest"
            coverage: "true"
          - php-version: '7.3'
            symfony-version: 4.4.*
            deps: "highest"
            coverage: "true"
          - php-version: '7.4'
            symfony-version: 4.4.*
            deps: "highest"
            coverage: "true"
          - php-version: '7.4'
            symfony-version: 5.1.*
            deps: "highest"
            coverage: "true"
          - php-version: '8.0'
            symfony-version: 5.4.*
            deps: "highest"
            coverage: "true"
          - php-version: '8.0'
            symfony-version: 6.0.*
            deps: "highest"
            coverage: "true"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
      - run: |
          sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "${{ matrix.symfony-version }}"/' composer.json;
      - name: "Install dependencies"
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.deps }}
          composer-options: --prefer-dist

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit"
        if: "${{ matrix.coverage != 'true' }}"

      - name: "Run PHPUnit with coverage"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"
        if: "${{ matrix.coverage == 'true' }}"

      - name: "Upload coverage"
        uses: codecov/codecov-action@v1
        if: "${{ matrix.coverage == 'true' }}"
        with:
          file: './coverage.xml'
          fail_ci_if_error: true

      - name: "Run PHP-CS-Fixer (E2E test)"
        run: "vendor/bin/php-cs-fixer fix --dry-run --diff"
        if: "${{ matrix.deps != 'lowest' }}"
  Psalm:
    name: "Psalm"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.0"

      - name: "Install dependencies"
        uses: ramsey/composer-install@v1

      - name: "Run Psalm"
        run: "vendor/bin/psalm"
